---
title: "Declaration Timing Analysis"
output: html_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../output/notebooks") })
---

```{r setup, echo=false}
# Libraries
pacman::p_load(tidymodels, visNetwork, sparkline, vip, survival, survminer, ggfortify)

# Load data
dec <- readRDS("../../data/processed/declarations.rds") %>% mutate(is_dec = as.factor(is_dec), innings = as.factor(innings))

# Ignore impossible declarations
dec <- dec %>% filter(!(lead <= -200 & innings == 2) & !(lead < 0 & innings == 3))

# Convert outcome to wicket or runs
dec <- dec %>% mutate(outcome = as.character(outcome)) %>%
  mutate(outcome = substr(outcome, 1,1)) %>% 
  mutate(outcome = as.factor(outcome))
dec$outcome <- droplevels(dec$outcome)
dec <- dec %>% add_column(is_wkt = as.factor(ifelse(grepl('^W', dec$outcome), "W", "no")))
dec <- dec %>% mutate(bat_score =  ifelse(outcome == "W", bat_score, bat_score + as.numeric(as.character(outcome))))


```




# Exploratory Data Analysis
```{r}
dec %>% filter(is_dec == "yes") %>%
  ggplot(aes(x = lead, y = inns_balls, color = innings)) + geom_point()
```



```{r}
dec %>% group_by(lead) %>% summarize(p = sum(is_dec == "yes")/n()) %>%
  filter(p != 0) %>%
  ggplot(aes(x = lead, y = 1 - p)) + geom_point() + geom_smooth()
```



## With hazard function
```{r}
haz <- dec %>% mutate(is_dec= abs(as.numeric(is_dec) - 1)) %>%
  group_by(lead) %>%
  summarise(event = sum(is_dec),
            total = n()) %>%
  mutate(hazard = event/total)

haz %>%
  ggplot(aes(x = lead, y = log(-log(1-hazard)))) +
  geom_point() +
  geom_smooth()

```



```{r}
dec %>% mutate(is_dec= abs(as.numeric(is_dec) - 1)) %>%
  group_by(inns_balls, innings) %>%
  summarise(event = sum(is_dec),
            total = n()) %>%
  mutate(hazard = event/total) %>%
  ggplot(aes(x = inns_balls, y = log(-log(1-hazard)), col = innings)) +
  geom_point() +
  geom_smooth()


```


# Modelling
```{r}
# Split into training, testing
split <- initial_split(dec, strata = is_dec)
train <- training(split)
test <- testing(split)

# Balanced training set
train_bal <- bind_rows(train %>% filter(is_dec == "yes"), sample_n(train %>% filter(is_dec == "no"), size = 11*nrow(train %>% filter(is_dec == "yes"))))

```


## Logistic Regression
```{r}
# Logistic regression
log_wf <- workflow() %>%
  add_recipe(recipe(is_dec ~ ., data = train_bal) %>%
                    step_rm(outcome, match_balls, game_id, wkts) %>%
                    step_naomit(all_predictors()) %>%
                    step_normalize(all_numeric()) %>%
                    step_dummy(is_wkt, innings) %>%
                    step_interact(terms = ~lead:starts_with("innings")) %>%
                    step_interact(terms = ~inns_balls:starts_with("innings"))) %>%
                add_model(logistic_reg() %>% set_engine("glm"))
log_fit <- log_wf %>% fit(data = train_bal)
tidy(log_fit)
```

### Evaluate on test set

```{r}
# Evaluate on test set
log_test <- test %>% add_column(log_fit %>% predict(new_data = test %>% mutate(bat_score_int = bat_score), type = "prob"))
log_test %>% roc_curve(truth = is_dec, estimate = .pred_yes, event_level = "second") %>% autoplot()
log_test %>% roc_auc(truth = is_dec, estimte = .pred_yes, event_level = "second") 
```


### Assumptions

```{r}
dec_log <- #log_fit %>% pull_workflow_prepped_recipe() %>% bake(train_bal) %>%
  train_bal %>% add_column(log_fit %>% predict(new_data = train_bal %>% mutate(bat_score_int = bat_score), type = "prob")) %>%
  mutate(logit = log(.pred_yes/(1-.pred_yes)))

# Linearity
ggplot(aes(inns_balls, logit, col = innings), data = dec_log) + geom_point()  +
  geom_smooth(method = "loess")

ggplot(aes(lead, logit, col = innings), data = dec_log) + geom_point()  +
  geom_smooth(method = "loess")

ggplot(aes(bat_score, logit), data = dec_log) + geom_point()  +
  geom_smooth(method = "loess")

```





## Cox Model

```{r}
edec <- dec %>% mutate(is_dec= as.numeric(is_dec) - 1)
cm <- coxph(Surv(lead, is_dec) ~ is_wkt + match_balls + innings, data = edec)
summary(cm)
```


```{r}
autoplot(survfit(cm))
```


```{r}
test.ph <- cox.zph(cm)
plot(test.ph[1])
```

### Evaluate on test


# (Prior) Prediction
```{r}
dec_pred <- readRDS("../data/rds/dec_pred.rds") %>% filter(dec_lead > -200) %>%
  mutate_at(c("innings"), as.factor)
```


## EDA
```{r}
skimr::skim(dec_pred)
```

```{r}
dec_pred %>% ggplot(aes(start_lead, dec_lead, col = innings)) + geom_point()
```


```{r}
dec_pred %>% ggplot(aes(seam_factor, dec_lead, col = innings)) + geom_point()
```




```{r}
dec_pred %>% ggplot(aes(start_match_balls, dec_lead, col = innings)) + geom_point()

```


## Fit a linear model
```{r}
dec_pred_no1 <- dec_pred %>% filter(innings != 1)
pred_lm_wf <- workflow() %>%
  add_recipe(
    recipe(dec_lead ~ innings + start_lead + start_match_balls + spin_factor + seam_factor, data = dec_pred_no1) %>%
      step_range(start_lead, start_match_balls, spin_factor, seam_factor) %>%
      step_BoxCox(start_lead, start_match_balls, spin_factor, seam_factor) %>%
      step_dummy(all_nominal()) %>%
      step_interact(terms = ~starts_with("innings"):start_lead)
  ) %>%
  add_model(
    linear_reg() %>% set_engine("lm")
  )
fit_pred_lm <- pred_lm_wf %>% fit(data = dec_pred_no1)
tidy(fit_pred_lm)
```


```{r}
vip(fit_pred_lm %>% pull_workflow_fit())
```


## Evaluate with CV
```{r}
dec_pred_cv <- vfold_cv(dec_pred_no1, n = 5, strata = dec_lead)
pred_lm_cv <- fit_pred_lm %>% fit_resamples(resamples = dec_pred_cv)
pred_lm_cv %>% collect_metrics()
```


## Assumption checking
```{r}
gglm::gglm((fit_pred_lm %>% pull_workflow_fit())$fit)

```






# Survival Analysis
```{r}
# Load match data
all_dec <- readRDS("../data/rds/all_dec.rds")

```



## Kaplan-Meier Analysis
```{r}
km_fit <- survfit(Surv(inns_balls, declared) ~ 1, data = all_dec)
autoplot(km_fit)
```

## By innings
```{r}
km_inn_fit <- survfit(Surv(inns_balls, declared) ~ 1, data = all_dec)
autoplot(km_fit)
```