---
title: "Test Match Batting - A Survival Analysis"
author: "L. Blake"
date: "24/03/2021"
output: html_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../output/notebooks") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse)
source("../pitch_qi.R")

bbb <- readRDS("../../data/processed/bbb_cleaned.RDS") %>%
  mutate_if(is.character, as.factor) %>%
  mutate_at(c("innings", "bat_position"), as.factor)

# Use better pitch factors:
bbb <- pqi_on_all(bbb) %>% 
  select(-c(bat_team_total_runs, 
            bat_team_total_wkts, bowl_team_total_runs, bowl_team_total_wkts,
            host_country, venue, winner, margin, outcome, toss_win, toss_elect,
            batter, bowler, dism_mode, bat_win_toss, 
            bat_home_away, bat_team, bowl_team, runs, extras, spell_balls,
            spell_runs, spell_wkts, pitch_factor, start_date, game_id, bowl_class, bowl_wkts, bowl_runs, spin_factor, seam_factor)) %>%
  na.omit()

# Collapse opening position into 1
bbb <- bbb %>% mutate(bat_position = fct_collapse(bat_position, open = c("1", "2")))

wkt_only <- bbb %>% filter(is_wkt == "W") %>% select(-is_wkt)

```

# The Data

```{r}
skimr::skim(wkt_only)
```



```{r}
wkt_only %>% ggplot(aes(x = bat_balls)) + geom_density(col = "purple", fill = "purple", alpha = 0.5)
```

```{r}
wkt_only %>% ggplot(aes(x = innings, y = bat_balls)) + geom_boxplot()
```


```{r}
wkt_only %>% ggplot(aes(x = bat_position, y = bat_balls)) + geom_boxplot()
```

```{r}
wkt_only %>% ggplot(aes(x = bat_avg, y = bat_balls)) + geom_point()
wkt_only %>% filter(career_bat_balls >= 1000) %>% ggplot(aes(x = bat_avg, y = bat_balls)) + geom_point()
```


```{r}
wkt_only %>% ggplot(aes(x = bat_sr, y = bat_balls)) + geom_point()
```

```{r}
wkt_only %>% ggplot(aes(sample = bat_sr)) + geom_qq() + geom_qq_line()
```

```{r}
wkt_only %>% ggplot(aes(x = bat_arm, y = bat_balls)) + geom_boxplot()
```


```{r}
wkt_only %>% ggplot(aes(x = bowl_avg, y = bat_balls)) + geom_point()
wkt_only %>% filter(career_bowl_balls >= 2000) %>% ggplot(aes(x = bowl_avg, y = bat_balls)) + geom_point()
```

```{r}
wkt_only %>% ggplot(aes(x = bowl_type, y = bat_balls)) + geom_boxplot()
```


# Approach 1 - Fixed Variables

```{r}
fixed <- bbb %>% select(c(innings, bat_position, bat_avg, career_bat_balls, bat_sr, bat_arm, pqi))
fixed
```


## Model 1 - Linear 


